/*
============================================================
CUSTOMER INTELLIGENCE PLATFORM
Module 03 - Sales Analysis
Author : Utkarsh Tiwari
============================================================
Objective:
Analyze sales performance, revenue trends, order values,
and payment behavior.
============================================================
*/


-- ==========================================================
-- Business Question 1
-- What is the total revenue generated?
-- ==========================================================

SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM payments;

/*
Business Insight:
- Shows the total revenue generated by the company.
- Acts as the primary business KPI.
*/


-- ==========================================================
-- Business Question 2
-- What is the average order value (AOV)?
-- ==========================================================

SELECT
    ROUND(AVG(payment_value), 2) AS average_order_value
FROM payments;

/*
Business Insight:
- Average amount customers spend per payment.
- Helps measure customer spending behavior.
*/


-- ==========================================================
-- Business Question 3
-- What is the highest payment made?
-- ==========================================================

SELECT
    MAX(payment_value) AS highest_payment
FROM payments;

/*
Business Insight:
- Identifies the largest single payment.
- Useful for detecting premium customers.
*/


-- ==========================================================
-- Business Question 4
-- What is the lowest payment made?
-- ==========================================================

SELECT
    MIN(payment_value) AS lowest_payment
FROM payments;

/*
Business Insight:
- Identifies the smallest payment recorded.
*/


-- ==========================================================
-- Business Question 5
-- Monthly Revenue Trend
-- ==========================================================

SELECT

    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,

    ROUND(SUM(p.payment_value),2) AS revenue

FROM orders o

JOIN payments p
ON o.order_id = p.order_id

GROUP BY month

ORDER BY month;

/*
Business Insight:
- Shows revenue growth month by month.
- Useful for trend analysis and forecasting.
*/


-- ==========================================================
-- Business Question 6
-- Number of Orders per Month
-- ==========================================================

SELECT

    DATE_TRUNC('month', order_purchase_timestamp) AS month,

    COUNT(*) AS total_orders

FROM orders

GROUP BY month

ORDER BY month;

/*
Business Insight:
- Measures business growth over time.
*/


-- ==========================================================
-- Business Question 7
-- Which payment methods are most popular?
-- ==========================================================

SELECT

    payment_type,

    COUNT(*) AS total_transactions,

    ROUND(SUM(payment_value),2) AS total_revenue

FROM payments

GROUP BY payment_type

ORDER BY total_transactions DESC;

/*
Business Insight:
- Shows preferred payment methods.
- Helps optimize payment options.
*/


-- ==========================================================
-- Business Question 8
-- Revenue by Order Status
-- ==========================================================

SELECT

    o.order_status,

    ROUND(SUM(p.payment_value),2) AS revenue

FROM orders o

JOIN payments p

ON o.order_id = p.order_id

GROUP BY o.order_status

ORDER BY revenue DESC;

/*
Business Insight:
- Delivered orders generate most revenue.
- Cancelled orders represent revenue loss.
*/


-- ==========================================================
-- Business Question 9
-- Top 10 Highest Revenue Orders
-- ==========================================================

SELECT

    p.order_id,

    ROUND(SUM(payment_value),2) AS revenue

FROM payments p

GROUP BY p.order_id

ORDER BY revenue DESC

LIMIT 10;

/*
Business Insight:
- Identifies high-value orders.
- Useful for premium customer analysis.
*/


-- ==========================================================
-- Business Question 10
-- Daily Revenue Trend
-- ==========================================================

SELECT

    DATE(order_purchase_timestamp) AS order_date,

    ROUND(SUM(payment_value),2) AS revenue

FROM orders o

JOIN payments p

ON o.order_id = p.order_id

GROUP BY order_date

ORDER BY order_date;

/*
Business Insight:
- Shows day-wise revenue.
- Useful for identifying sales spikes.
*/


-- ==========================================================
-- Business Question 11
-- Revenue by State
-- ==========================================================

SELECT

    c.customer_state,

    ROUND(SUM(p.payment_value),2) AS revenue

FROM customers c

JOIN orders o
ON c.customer_id = o.customer_id

JOIN payments p
ON o.order_id = p.order_id

GROUP BY c.customer_state

ORDER BY revenue DESC;

/*
Business Insight:
- Shows which states contribute the highest revenue.
- Useful for regional business strategy.
*/


-- ==========================================================
-- Business Question 12
-- Revenue Contribution Percentage by State
-- ==========================================================

SELECT

    c.customer_state,

    ROUND(SUM(payment_value),2) AS revenue,

    ROUND(
        SUM(payment_value) * 100 /
        (SELECT SUM(payment_value) FROM payments),
        2
    ) AS revenue_percentage

FROM customers c

JOIN orders o
ON c.customer_id = o.customer_id

JOIN payments p
ON o.order_id = p.order_id

GROUP BY c.customer_state

ORDER BY revenue DESC;

/*
Business Insight:
- Displays each state's contribution
  to overall company revenue.
*/


-- ==========================================================
-- End of Sales Analysis
-- ==========================================================