/*
============================================================
CUSTOMER INTELLIGENCE PLATFORM
Module 06 - Payment Analysis
Author : Utkarsh Tiwari
============================================================
Objective:
Analyze customer payment behavior, revenue,
installments and payment methods.
============================================================
*/


-- ==========================================================
-- Business Question 1
-- Which payment methods are most used?
-- ==========================================================

SELECT
    payment_type,
    COUNT(*) AS total_transactions
FROM payments
GROUP BY payment_type
ORDER BY total_transactions DESC;

/*
Business Insight:
- Identifies the most preferred payment methods.
- Helps optimize checkout experience.
*/


-- ==========================================================
-- Business Question 2
-- Revenue generated by each payment method
-- ==========================================================

SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS revenue
FROM payments
GROUP BY payment_type
ORDER BY revenue DESC;

/*
Business Insight:
- Shows which payment method generates
  the highest revenue.
*/


-- ==========================================================
-- Business Question 3
-- Average payment amount by payment method
-- ==========================================================

SELECT
    payment_type,
    ROUND(AVG(payment_value),2) AS average_payment
FROM payments
GROUP BY payment_type
ORDER BY average_payment DESC;

/*
Business Insight:
- Helps understand spending patterns
  for each payment method.
*/


-- ==========================================================
-- Business Question 4
-- Highest payment made
-- ==========================================================

SELECT
    MAX(payment_value) AS highest_payment
FROM payments;

/*
Business Insight:
- Identifies premium purchases.
*/


-- ==========================================================
-- Business Question 5
-- Lowest payment made
-- ==========================================================

SELECT
    MIN(payment_value) AS lowest_payment
FROM payments;

/*
Business Insight:
- Useful for identifying very small transactions.
*/


-- ==========================================================
-- Business Question 6
-- Average number of installments
-- ==========================================================

SELECT
    ROUND(AVG(payment_installments),2)
AS average_installments
FROM payments;

/*
Business Insight:
- Shows customers' tendency to pay
  using installments.
*/


-- ==========================================================
-- Business Question 7
-- Installment Distribution
-- ==========================================================

SELECT

payment_installments,

COUNT(*) AS transactions

FROM payments

GROUP BY payment_installments

ORDER BY payment_installments;

/*
Business Insight:
- Shows the popularity of installment plans.
*/


-- ==========================================================
-- Business Question 8
-- Top 10 Highest Payment Transactions
-- ==========================================================

SELECT

order_id,

payment_type,

payment_value

FROM payments

ORDER BY payment_value DESC

LIMIT 10;

/*
Business Insight:
- Identifies highest-value purchases.
*/


-- ==========================================================
-- Business Question 9
-- Average Revenue per Payment Type
-- ==========================================================

SELECT

payment_type,

ROUND(

SUM(payment_value)/COUNT(*),

2

) AS average_revenue

FROM payments

GROUP BY payment_type

ORDER BY average_revenue DESC;

/*
Business Insight:
- Useful for comparing payment methods.
*/


-- ==========================================================
-- Business Question 10
-- Monthly Revenue by Payment Type
-- ==========================================================

SELECT

DATE_TRUNC(
'month',
o.order_purchase_timestamp
) AS month,

p.payment_type,

ROUND(

SUM(payment_value),

2

) AS revenue

FROM payments p

JOIN orders o

ON p.order_id = o.order_id

GROUP BY

month,
payment_type

ORDER BY

month,
payment_type;

/*
Business Insight:
- Tracks payment trends over time.
*/


-- ==========================================================
-- Business Question 11
-- Payment Method Percentage
-- ==========================================================

SELECT

payment_type,

COUNT(*) AS transactions,

ROUND(

COUNT(*)*100.0/
(SELECT COUNT(*) FROM payments),

2

) AS percentage

FROM payments

GROUP BY payment_type

ORDER BY percentage DESC;

/*
Business Insight:
- Shows market share of each payment method.
*/


-- ==========================================================
-- Business Question 12
-- Revenue by Installment Count
-- ==========================================================

SELECT

payment_installments,

ROUND(

SUM(payment_value),

2

) AS revenue

FROM payments

GROUP BY payment_installments

ORDER BY payment_installments;

/*
Business Insight:
- Evaluates the impact of installment plans
  on revenue.
*/


-- ==========================================================
-- End of Payment Analysis
-- ==========================================================